/* October qualification views. Strict hard-gate model from supplied September workbook.
 * Unknown no-site evidence cannot create a scored / priced / outreach-approved lead.
 */
(function(){
"use strict";
var state={view:"dashboard",records:[],data:null,query:""};
var doc=document,root=doc.getElementById("view-content"),modal=doc.getElementById("modal-overlay");
var labels={dashboard:"DASHBOARD",premium:"PREMIUM 70–100K",new:"NEW 40–50K",queue:"VERIFICATION QUEUE",qa:"QA / DEFERRED",method:"METHODOLOGY"};
var cols=["Company","IČO","City","Sector","Legal / budget signal","Website gate","No-site confidence","Score","Suggested package","Next check"];
function escapeText(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function money(n){return n===null||n===undefined?"—":new Intl.NumberFormat("en-GB",{maximumFractionDigits:0}).format(n)+" CZK"}
function safeUrl(url){try{var u=new URL(String(url));return u.protocol==="https:"||u.protocol==="http:"?u.href:""}catch(e){return ""}}
function verifiedGate(r){return !!(r&&r.website_gate==="PASS — repeated exact-entity verification"&&r.no_site_confidence!==null&&r.no_site_confidence>=.9&&r.operating_business_verified===true)}
function salesQualified(r){return verifiedGate(r)&&Number.isFinite(r.score)&&r.score>=0&&r.package_czk>0}
function tag(v){return '<span class="tag '+(v==="high"?"hold":v==="defer"?"defer":v==="pass"?"pass":"fail")+'">'+escapeText(v==="high"?"PRIORITY RESEARCH":v==="defer"?"DEFERRED / QA":v==="pass"?"QUALIFIED":v)+"</span>"}
function stat(label,value,sub,icon,dark){return '<article class="stat'+(dark?' dark':'')+'"><div class="stat-top"><span>'+escapeText(label)+'</span><i aria-hidden="true">'+escapeText(icon)+'</i></div><div class="stat-value">'+escapeText(value)+'</div><div class="stat-foot">'+sub+'</div></article>'}
function head(num,title,subtitle,note){return '<header class="panel-header"><div><div class="kicker">'+num+'</div><h2>'+title+'</h2>'+(subtitle?'<p>'+subtitle+'</p>':'')+'</div>'+(note?'<span class="side-note">'+note+'</span>':'')+'</header>'}
function empty(title,desc){return '<div class="empty"><div class="empty-icon" aria-hidden="true">⌕</div><h3>'+title+'</h3><p>'+desc+'</p></div>'}
function priorityCard(r,i){return '<article class="priority"><div class="rank">RESEARCH '+String(i+1).padStart(2,"0")+' / '+escapeText(r.sector)+'</div><h3>'+escapeText(r.name)+'</h3><p>'+escapeText(r.sector_offer)+'</p><div class="minirow"><span>GATE: HOLD</span><button type="button" data-dossier="'+escapeText(r.id)+'">View evidence ↗</button></div></article>'}
function sourceAnchor(url,label){url=safeUrl(url);return url?'<a href="'+escapeText(url)+'" target="_blank" rel="noopener noreferrer">'+escapeText(label||url)+' ↗</a>':""}
function row(r,i,short){var legal=r.financial_evidence||"No verified scale",score=salesQualified(r)?String(r.score):"—",packageV=salesQualified(r)?money(r.package_czk):"—";return '<tr><td><span class="company">'+escapeText(r.name)+'</span><span class="secondary">'+escapeText(r.ico||"IČO needs checking")+'</span></td><td>'+escapeText(r.city)+'</td><td>'+escapeText(r.sector)+'</td><td>'+tag(r.review_priority==="Priority research"?"high":"defer")+'</td>'+(short?'':'<td class="description">'+escapeText(legal)+'</td><td>'+escapeText(r.no_site_confidence===null?"NOT VERIFIED":Math.round(r.no_site_confidence*100)+"%")+'</td><td>'+score+'</td><td>'+escapeText(packageV)+'</td>')+'<td><button type="button" class="open-dossier" data-dossier="'+escapeText(r.id)+'">Dossier ↗</button></td></tr>'}
function makeTable(items,short){var headers=short?["Company / IČO","City","Sector","Qualification","Evidence"]:["Company / IČO","City","Sector","Qualification","Budget signal","No-site confidence","Score","Price","Dossier"];return '<div class="table-scroller"><table class="table"><thead><tr>'+headers.map(function(h){return '<th>'+escapeText(h)+'</th>'}).join("")+'</tr></thead><tbody>'+items.map(function(r,i){return row(r,i,short)}).join("")+'</tbody></table></div>'}
function searchBar(count){return '<div class="table-tools"><input class="search" id="company-search" type="search" aria-label="Search reviewed companies" placeholder="Search company, IČO, city or sector…" value="'+escapeText(state.query)+'"><span class="table-count" id="visible-count">'+count+' ENTRIES</span></div>'}
function filtered(items){var needle=state.query.trim().toLocaleLowerCase();if(!needle)return items;return items.filter(function(r){return [r.name,r.ico,r.city,r.sector,r.decision_reason].some(function(x){return String(x||"").toLocaleLowerCase().includes(needle)})})}
function listPanel(items,n,title,sub,short){var visible=filtered(items);return '<section class="panel">'+head(n,title,sub,String(visible.length).padStart(2,"0")+" / "+String(items.length).padStart(2,"0"))+searchBar(visible.length)+(visible.length?makeTable(visible,short):empty("No matching companies","Try a different company, IČO or sector."))+'<div class="footer-note">Registration records and website-search non-results are not proof of active trading or missing sites.</div></section>'}
function splitCount(){var q=state.records.filter(salesQualified);return{qualified:q.length,pr:state.records.filter(function(x){return x.review_priority==="Priority research"}),defer:state.records.filter(function(x){return x.review_priority==="Deferred / QA"})}}
function dashboard(){var c=splitCount();return '<section class="stat-grid">'+stat("Premium qualified",0,"<b>70–100K</b> strict gate","◈")+stat("New company qualified",0,"<b>40–50K</b> strict gate","↗")+stat("QA / deferred",c.defer.length,"<b>NOT OUTREACH</b> insufficient evidence","⊘")+stat("Qualified pipeline","0 CZK","<b>NO ASSUMED REVENUE</b> until gate passes","◎",true)+'</section>'+
'<div class="section-split"><section class="panel">'+head("01 / CURRENT QUALIFICATION","No premature sales leads.","None of the 24 October companies has the combination of verified missing site, operating proof, budget signal and contact needed by the workbook’s hard gate.","0 / 24")+
'<div class="muted-notice"><strong>Screened:</strong> 24 · <strong>Priority follow-ups:</strong> 7 · <strong>Deferred:</strong> 17 · <strong>Outreach-ready:</strong> 0. The prior September workbook’s 7 premium + 18 new qualified results are historical and have not been reverified for October.</div>'+
'<div style="padding:0 24px 22px"><div class="compare-key"><span></span>Exact IČO and official registry source</div><div class="compare-key"><span></span>Independent first-party domain attribution</div><div class="compare-key"><span></span>Operating activity, contact and scale evidence</div><div class="compare-key"><span></span>Only then: package score and outreach approval</div></div></section>'+
'<aside class="brief"><div class="kicker">02 / NEXT ACTION</div><h2>Verify before you pitch.</h2><p>The October prospects are promising industries, not validated buyers. Prioritize evidence of actual customer jobs, public company contacts and a repeatable website ownership check. Do not score or price incomplete profiles.</p><div class="info">Next review: company operations → exact entity domain check → direct contact → buyer need.</div></aside></div>'+
'<section class="panel">'+head("03 / PRIORITY RESEARCH","Seven to investigate further.","These industries could suit a website project, but none currently passes the workbook’s no-site requirement.","7 CANDIDATES")+
'<div class="priority-list">'+c.pr.map(priorityCard).join("")+'</div></section>'}
function qualifiedView(kind){var premium=kind==="premium",max=premium?"70–100k":"40–50k",c=state.records.filter(function(r){return salesQualified(r)&&r.package_group===(premium?"Premium 70-100k":"New 40-50k")});
var sub=premium?"Operating scale ≥50m CZK, no owned-domain site verified, and a compelling ROI case.":"New registration, researched absence of official company site, verified operator/contact and economic fit.";
return '<section class="stat-grid">'+stat("Qualified companies",c.length,"<b>"+max.toUpperCase()+" CZK</b> package tier","◈")+stat("Verified no-site",c.length,"<b>EXACT ENTITY</b> gate cleared","◎")+stat("Unverified names",state.records.length,"<b>NOT QUALIFIED</b> until checked","↗")+stat("Package pipeline",money(c.reduce(function(s,r){return s+r.package_czk},0)),"<b>ONLY PASSED</b> companies count","▦",true)+'</section><section class="panel">'+head("01 / "+(premium?"PREMIUM":"NEW COMPANY").toUpperCase(),"Qualified "+max+" CZK candidates",sub,"STRICT NO-SITE")+(c.length?makeTable(c,false):empty("No companies passed the gate","The October list contains no independently confirmed, first-party-website-free company with sufficient operating and financial evidence. We are intentionally showing an empty qualified list instead of inventing high scores or prices."))+'<div class="footer-note">The uploaded September example used this package tier for its September research cut. Those companies are not silently marked as October-qualified.</div></section>'}
function queue(){var c=state.records.filter(function(r){return r.review_priority==="Priority research"});return '<section class="stat-grid">'+stat("Priority research",c.length,"<b>NOT QUALIFIED</b> yet","↗")+stat("Site verified missing",0,"<b>NO SITE PASS</b> recorded","◎")+stat("Buyer contact verified",0,"<b>EXACT NEW ENTITIES</b> not established","⌁")+stat("Potential pipeline","0 CZK","<b>NOT FORECAST</b> until qualified","◈",true)+'</section>'+listPanel(c,"01 / PRIORITY RESEARCH","Seven companies requiring proof","The right sector is not enough. Open a dossier for the specific blocker and original source.",false)}
function qa(){var c=state.records.filter(function(r){return r.review_priority==="Deferred / QA"});return '<section class="stat-grid">'+stat("Deferred / QA",c.length,"<b>NO OUTREACH</b> until verified","⊘")+stat("Hard website rejects",0,"<b>NO FALSE MATCHES</b> to existing sites","◎")+stat("Unverified operations",24,"<b>ACROSS REVIEW</b> companies","⌁")+stat("Qualified revenue","0 CZK","<b>NOT COUNTED</b> in forecast","◈",true)+'</section>'+listPanel(c,"01 / QA & DEFERRALS","Excluded from the active pitch list","These entries were deferred for geography, missing operator evidence, broad licenses or a possible already-existing related brand site. Deferred does not mean fraudulent, inactive or definitively website-equipped.",false)}
function method(){return '<section class="method-grid">'+
'<article class="method-card"><div class="kicker">GROUP 01 / PREMIUM 70–100K</div><h3>Established commercial businesses</h3><p>Eligibility: operating scale ≥ 50m CZK, first-party no-site gate PASS and demonstrable business-website ROI.</p><ul><li>Financial strength <b>35</b></li><li>No-site confidence <b>30</b></li><li>Website ROI <b>20</b></li><li>Market / reach <b>15</b></li></ul><div class="muted-notice" style="margin:0">Score ≥90 → 100,000 CZK · 82–89 → 80,000 CZK · 72–81 → 70,000 CZK · Below 72 → HOLD</div></article>'+
'<article class="method-card"><div class="kicker">GROUP 02 / NEW 40–50K</div><h3>Newly registered companies</h3><p>Eligibility: October registration, proven no attributable first-party company domain, operating activity and credible sector/buyer evidence.</p><ul><li>Sector economics <b>30</b></li><li>Budget / legal signal <b>20</b></li><li>Launch urgency <b>25</b></li><li>No-site score <b>15</b></li><li>Market fit <b>10</b></li></ul><div class="muted-notice" style="margin:0">Score ≥85 → 50,000 CZK · Below 85 → 40,000 CZK, only after gate passes. Registered capital is not buyer cash.</div></article>'+
'<article class="method-card"><div class="kicker">HARD GATE / VERIFICATION</div><h3>Six mandatory domain checks</h3><ol class="step-list">'+["Exact legal company name in quotation marks","Exact legal name + correct IČO","Exact name with website / web / official-domain terms","Search directories, public registry contact, likely brand domains","Reject site-free claim if exact entity owns a business website","For group/SPV, distinguish no dedicated legal-entity website from an existing group/brand website"].map(function(x){return '<li><span>'+escapeText(x)+'</span></li>'}).join("")+'</ol></article>'+
'<article class="method-card"><div class="kicker">DATA HONESTY / OCTOBER</div><h3>What this dashboard does not assume</h3><p>All 24 come from the user-provided Kurzy listing. Some entries have independent commercial-register sources; others need exact IČO checks. Nothing is labelled site-free because searches returned no result.</p><ul><li>Search failed / blocked <b>HOLD</b></li><li>Unverified contact / workshop <b>HOLD</b></li><li>Existing same-name domain <b>CHECK IČO</b></li><li>Share capital only <b>NOT BUDGET</b></li><li>Qualified package forecast <b>0 CZK</b></li></ul><p>Original supplied workbook: <strong>25 September 2026</strong> historic research; this page: <strong>9 October 2026</strong> separate investigation. Source: '+sourceAnchor("https://rejstrik-firem.kurzy.cz/seznam-10/","Kurzy registry list")+'.</p></article></section>'}
function render(){var v=state.view;doc.getElementById("breadcrumb-view").textContent=labels[v];doc.querySelectorAll("#main-nav button").forEach(function(b){b.classList.toggle("active",b.dataset.view===v);b.setAttribute("aria-current",b.dataset.view===v?"page":"false")});root.innerHTML=v==="dashboard"?dashboard():v==="premium"||v==="new"?qualifiedView(v):v==="queue"?queue():v==="qa"?qa():method();bindDossiers();var input=doc.getElementById("company-search");if(input){input.addEventListener("input",function(){state.query=input.value;var pos=input.selectionStart;var wrap=doc.querySelector(".table-scroller"),pane=wrap?wrap.parentNode:null;var items=(v==="queue"?state.records.filter(function(r){return r.review_priority==="Priority research"}):state.records.filter(function(r){return r.review_priority==="Deferred / QA"}));var matches=filtered(items), count=doc.getElementById("visible-count");if(wrap){wrap.outerHTML=matches.length?makeTable(matches,false):empty("No matching companies","Try a different company, IČO or sector.");}else if(pane){var e=pane.querySelector(".empty");if(e)e.outerHTML=matches.length?makeTable(matches,false):empty("No matching companies","Try a different company, IČO or sector.");}if(count)count.textContent=matches.length+" ENTRIES";bindDossiers();})}}
function showDossier(id){var r=state.records.find(function(x){return x.id===id});if(!r)return;var nodes=[
["Website check","Hard gate: HOLD. "+r.website_status+". No-site confidence and score have intentionally not been assigned."],
["Registered / operating evidence",r.decision_reason],
["Legal or financial signal",r.financial_evidence+" — registered capital never proves purchasing capacity."],
["Potential website project",r.sector_offer],
["Next verification",r.next_check],
["Sources",'<div class="link-list">'+(r.source_urls||[]).map(function(x){return sourceAnchor(x)}).join("")+'</div>']
];doc.getElementById("detail-body").innerHTML='<div class="detail-content"><div class="kicker">VERIFICATION REQUIRED / '+escapeText(r.checked_at)+'</div><h2 id="detail-heading">'+escapeText(r.name)+'</h2><div class="sub">'+escapeText(r.ico||"IČO not verified")+' · '+escapeText(r.city)+' · '+escapeText(r.sector)+'</div>'+tag(r.review_priority==="Priority research"?"high":"defer")+'<div class="dossier-group"><h3>Sales readiness</h3><p><strong>NOT APPROVED.</strong> No confirmed buyer, absent owned-domain website or verifiable financial capacity. Suggested price: —.</p></div>'+nodes.map(function(x){return '<div class="dossier-group"><h3>'+escapeText(x[0])+'</h3><p>'+(x[0]==="Sources"?x[1]:escapeText(x[1]))+'</p></div>'}).join("")+'</div>';
modal.hidden=false;doc.body.style.overflow="hidden";doc.getElementById("close-panel").focus()}
function close(){modal.hidden=true;doc.body.style.overflow=""}
function bindDossiers(){doc.querySelectorAll("[data-dossier]").forEach(function(b){b.addEventListener("click",function(){showDossier(b.dataset.dossier)})})}
function exportCsv(){var items=state.view==="queue"?state.records.filter(function(r){return r.review_priority==="Priority research"}):state.view==="qa"?state.records.filter(function(r){return r.review_priority==="Deferred / QA"}):state.view==="premium"||state.view==="new"?state.records.filter(salesQualified):state.records;var heads=["Company","ICO","Registered date","City","Sector","Research priority","Website gate","No-site confidence","Score","Package CZK","Legal financial evidence","Potential offer","Research decision","Next action","Sources","Outreach status"];var csv=[heads].concat(items.map(function(r){return [r.name,r.ico||"",r.registration_date,r.city,r.sector,r.review_priority,r.website_gate,r.no_site_confidence==null?"":r.no_site_confidence,r.score==null?"":r.score,r.package_czk==null?"":r.package_czk,r.financial_evidence,r.sector_offer,r.decision_reason,r.next_check,(r.source_urls||[]).join(" | "),r.outreach_status]})).map(function(row){return row.map(function(x){return '"'+String(x==null?"":x).replace(/"/g,'""')+'"'}).join(",")}).join("\r\n");var url=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"}));var a=doc.createElement("a");a.href=url;a.download="fieldnotes-oct-2026-"+state.view+".csv";doc.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},500)}
doc.getElementById("main-nav").addEventListener("click",function(e){var b=e.target.closest("button[data-view]");if(!b)return;state.view=b.dataset.view;state.query="";render();window.scrollTo({top:0,behavior:"instant"})});
doc.getElementById("csv-btn").addEventListener("click",exportCsv);
doc.getElementById("close-panel").addEventListener("click",close);
modal.addEventListener("click",function(e){if(e.target===modal)close()});
doc.addEventListener("keydown",function(e){if(e.key==="Escape"&&!modal.hidden)close()});
fetch("./data/october-review.json",{cache:"no-store"}).then(function(r){if(!r.ok)throw Error("HTTP "+r.status);return r.json()}).then(function(d){if(!d||!Array.isArray(d.records)||d.records.length!==24)throw Error("Incomplete October dataset");if(d.records.some(function(r){return r.package_czk!=null&&!salesQualified(r)}))throw Error("Ungated package detected");state.records=d.records;state.data=d;doc.getElementById("nav-premium").textContent=String(d.records.filter(function(r){return salesQualified(r)&&r.package_group==="Premium 70-100k"}).length);doc.getElementById("nav-new").textContent=String(d.records.filter(function(r){return salesQualified(r)&&r.package_group==="New 40-50k"}).length);doc.getElementById("nav-queue").textContent=String(d.summary.priority_research);doc.getElementById("nav-qa").textContent=String(d.summary.deferred_qa);doc.getElementById("data-message").innerHTML='<span class="signal"></span>24 October registrations screened · 7 priority research · 17 deferred · <strong>0 outreach approved</strong> · Source snapshot 09 Oct 2026';render()}).catch(function(e){doc.getElementById("data-message").classList.add("error");doc.getElementById("data-message").textContent="October data could not be verified: "+e.message;root.innerHTML=empty("Research unavailable","Do not assume zero or qualified leads from a failed data load. Check GitHub Pages.");});
})();